title: NOVA
baseline: Santé Intégrée
address: Rte du Simplon 16, 1094 Paudex
practitioners_url: "#practitioners"
headline: La santé se construit ensemble.
cta:
  text: Contactez-nous
  url: "#contact"
contact:
  email: sarah.dionne@novasante.ch
  phone: +41 76 839 30 08
collections_dir: my_collections
collections:
  practitioners:
    output: true
    permalink: /:name/
    sort_by: order, last
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      title: "NOVA Santé Intégrée | Espace Thérapeutique & Coordination de Soins à Paudex"
      description: "Découvrez NOVA Santé Intégrée, un espace thérapeutique à Paudex. Nous coordonnons vos parcours de soins en favorisant la collaboration entre approches contemporaines, traditionnelles et complémentaires pour des accompagnements personnalisés et efficaces."
  - scope:
      path: ""
      type: practitioners
    values:
      layout: practitioner
      